### ISSUE TITLE
New Project > AI Suggested Dates

### ISSUE THREAD

**Issue by tompieroni** [theodi/consequence-scanning-activity#6]
AI to suggest dates for actions does not produce a date. In the data table output, the value is DD/MM/YYYY.

The field is blank if a date is not selected, and the AI plugin is not selected.

<img width="909" alt="image" src="https://github.com/theodi/consequence-scanning-activity/assets/26923856/f62dcf96-2a11-4516-94cd-81d99d88b934">

Note the date column:

<img width="937" alt="image" src="https://github.com/theodi/consequence-scanning-activity/assets/26923856/28bc499e-1f66-4ed6-b6f9-6b2ed1cec7d6">

**Comment by jschof1** [comment]
We decided to remove the AI date suggestions in the end.
