### ISSUE TITLE
Assigning Actions

### ISSUE THREAD

**Issue by tompieroni** [theodi/consequence-scanning-activity#7]
When assigning actions, the wording on the button to automate categorisation as Act, Monitor or Influence is confusing. It currently reads "fill measure using AI" and it should say "Suggest AIM category using AI"

<img width="776" alt="image" src="https://github.com/theodi/consequence-scanning-activity/assets/26923856/614a6b94-0b5c-4fa8-abdf-cab8a443a1d6">

**Comment by jschof1** [comment]
fixed in commit #168ec25
