### ISSUE TITLE
Download PDF Report causes tool to hang

### ISSUE THREAD

**Issue by tompieroni** [theodi/consequence-scanning-activity#8]
As a user, if you try to download the data in pdf format, the page updates to show the pdf, rather than opening in a new tab or downloading the file directly. 

Due to this, if the user clicks back and returns to the tool, the pop-up with download options cannot be closed and no links are clickable. Although clicking a link in the navigation will update the URL, the page will not update.

<img width="1239" alt="image" src="https://github.com/theodi/consequence-scanning-activity/assets/26923856/7ae7fa65-9f94-4334-9e6f-2b6ba8ca77cd">

**Comment by jschof1** [comment]
fixed in commit #168ec25
